[package]
name = "libafl_structured_mutators_derive"
version.workspace = true
authors = ["Ely Ronnen"]
description = "Derive proc-macro crate for LibAFL mutators"
documentation = "https://docs.rs/libafl_mutators_derive"
repository = "https://github.com/AFLplusplus/LibAFL/"
readme = "README.md"
keywords = ["fuzzing", "testing", "mutator"]
edition = "2024"
categories = [
  "development-tools::testing",
  "emulators",
  "embedded",
  "os",
  "no-std",
]

[features]
tracing-debug = ["tracing"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2 = "1"
libafl = { workspace = true }
tracing = { version = "0.1", features = ["release_max_level_info"], optional = true }

[lints]
workspace = true
