[package]
name = "libafl_structured_mutators"
version.workspace = true
authors = ["Ely Ronnen"]
description = "A collection of structure-aware mutators for LibAFL"
edition = "2024"

[features]
default = ["derive"]
derive = ["libafl_structured_mutators_derive"]
tracing-debug = ["tracing", "libafl_structured_mutators_derive/tracing-debug"]

[dependencies]
libafl = { workspace = true, default-features = false }
libafl_bolts = { workspace = true, default-features = false }
libafl_structured_mutators_derive = { workspace = true, default-features = false, optional = true }
tracing = { version = "0.1", features = ["release_max_level_info"], optional = true }

hashbrown = { workspace = true, features = [
  "serde",
], default-features = false }

[lints]
workspace = true
